# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
#import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('slug', models.SlugField(null=True, verbose_name='\u0422\u0440\u0430\u043d\u0441\u043b\u0438\u0442')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'category',
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Stranica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('text_block', models.TextField(default='', verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e')),
                ('active', models.BooleanField(verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c')),
                ('nomer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0432\u043b\u043e\u0436\u0435\u043d\u043d\u043e\u0441\u0442\u0438')),
                ('datetime', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('title_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u0430\u0439\u0442\u043b')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u0414\u0435\u0441\u043a\u0440\u0438\u043f\u0448\u043e\u043d')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u0435\u0439\u0432\u043e\u0440\u0434\u0441')),
                ('categorypost', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stranica.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
                'verbose_name_plural': '\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
    ]
