# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stranica', '0002_auto_20171116_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stranica',
            name='datetime',
        ),
        migrations.AddField(
            model_name='category',
            name='nomer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0432\u043b\u043e\u0436\u0435\u043d\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='stranica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='stranica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
