# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stranica', '0004_auto_20171116_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nomer_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0432\u043b\u043e\u0436\u0435\u043d\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='stranica',
            name='nomer_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0432\u043b\u043e\u0436\u0435\u043d\u043d\u043e\u0441\u0442\u0438'),
        ),
    ]
