# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stranica', '0006_auto_20171117_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('tagslug', models.SlugField(null=True, verbose_name='\u0422\u0440\u0430\u043d\u0441\u043b\u0438\u0442')),
            ],
            options={
                'db_table': 'tags',
                'verbose_name': '\u0422\u0435\u0433\u0438 \u0440\u0430\u0437\u0434\u0435\u043b\u043e\u0432',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='stranica',
            name='tags',
            field=models.ManyToManyField(to='stranica.Tags', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
