# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stranica', '0007_auto_20171118_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stranica',
            name='tags',
        ),
        migrations.AlterField(
            model_name='stranica',
            name='categorypost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stranica.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
