# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 17:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stranica', '0008_auto_20171123_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('podkluchenie', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u041f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 SSHFS')),
                ('adminka', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u0410\u0434\u043c\u0438\u043d\u043a\u0430 \u0441\u0430\u0439\u0442\u0430')),
                ('yandex', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u042f\u043d\u0434\u0435\u043a\u0441 \u043f\u043e\u0447\u0442\u0430')),
                ('google', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Google \u043f\u043e\u0447\u0442\u0430')),
                ('phpmyadmin', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Phpmyadmin')),
                ('ftp', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u0424\u0442\u043f \u0434\u043e\u0441\u0442\u0443\u043f')),
                ('billing', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u0411\u0438\u043b\u043b\u0438\u043d\u0433 \u043f\u0430\u043d\u0435\u043b\u044c')),
                ('isp', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Isp \u043f\u0430\u043d\u0435\u043b\u044c')),
                ('registrator', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440 \u0434\u043e\u043c\u0435\u043d\u0430')),
                ('drugoe', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f\u044b \u0434\u0440\u0443\u0433\u0438\u0435')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0441\u0442\u0443\u043f\u044b',
                'verbose_name_plural': '\u0414\u043e\u0441\u0442\u0443\u043f\u044b \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
    ]
