# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stranica', '0009_dostup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dostup',
            options={'verbose_name': '\u0414\u043e\u0441\u0442\u0443\u043f\u044b \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b', 'verbose_name_plural': '\u0414\u043e\u0441\u0442\u0443\u043f\u044b'},
        ),
        migrations.AlterModelOptions(
            name='stranica',
            options={'ordering': ['nomer_id'], 'verbose_name': '\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b', 'verbose_name_plural': '\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'},
        ),
        migrations.AddField(
            model_name='stranica',
            name='template_name',
            field=models.CharField(blank=True, help_text="\u041f\u0440\u0438\u043c\u0435\u0440: 'flatpages/contact_page.html'. \u0415\u0441\u043b\u0438 \u043d\u0435 \u0443\u043a\u0430\u0437\u0430\u043d\u043e,  \u0441\u0438\u0441\u0442\u0435\u043c\u0430 \u0431\u0443\u0434\u0435\u0442 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c 'flatpages/default.html'.", max_length=70, verbose_name='template name'),
        ),
        migrations.AddField(
            model_name='stranica',
            name='url',
            field=models.CharField(db_index=True, default='1', max_length=100, verbose_name='URL'),
        ),
    ]
