# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stranica', '0010_auto_20171220_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stranica',
            name='url',
        ),
        migrations.AlterField(
            model_name='stranica',
            name='template_name',
            field=models.CharField(blank=True, help_text="\u041f\u0440\u0438\u043c\u0435\u0440: 'flatpages/contact_page.html'. \u0415\u0441\u043b\u0438 \u043d\u0435 \u0443\u043a\u0430\u0437\u0430\u043d\u043e,  \u0441\u0438\u0441\u0442\u0435\u043c\u0430 \u0431\u0443\u0434\u0435\u0442 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c 'flatpages/default.html'.", max_length=70, verbose_name='\u0412\u044b\u0431\u043e\u0440 \u0448\u0430\u0431\u043b\u043e\u043d\u0430'),
        ),
    ]
