# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stranica', '0011_auto_20171221_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svetofor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0426\u0432\u0435\u0442')),
                ('class_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u041a\u043b\u0430\u0441\u0441\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': '\u0421\u0432\u0435\u0442\u043e\u0444\u043e\u0440',
                'verbose_name_plural': '\u0421\u0432\u0435\u0442\u043e\u0444\u043e\u0440',
            },
        ),
        migrations.AddField(
            model_name='stranica',
            name='svetofor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stranica.Svetofor', verbose_name='\u0421\u0432\u0435\u0442\u043e\u0444\u043e\u0440'),
        ),
    ]
