# -*- coding: utf-8 -*-
"""
Django settings for wiki project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

DEBUG = False

ALLOWED_HOSTS = [
'92.53.120.40',
'wiki.starcev.biz',
]

DATABASES = {
  'default': {
      'ENGINE': 'django.db.backends.postgresql_psycopg2',
      'NAME': 'wiki',
      'USER': 'wiki',
      'PASSWORD': '649970',
      'HOST': 'localhost',
      'PORT': '',
            }
}


EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_USER = 'axik-1@yandex.ru'
EMAIL_HOST_PASSWORD = 'Appleservice912'
EMAIL_PORT = 587
EMAIL_USE_TLS = True



BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_PATH = os.path.abspath(os.path.dirname(__file__))

STATIC_ROOT = os.path.join(BASE_DIR, 'static/root')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
  os.path.join(BASE_DIR, 'static'),
  os.path.join(BASE_DIR, 'static/theme/default'),
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATIC_URL = '/static/theme/default/'
MEDIA_URL = '/media/'
ADMIN_MEDIA_PREFIX = '/static/admin/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [

            os.path.join(BASE_DIR, 'templates/default'),

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
   
            ],
        },
    },
]



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&fs$sw+kge=6#k126exd=9yum!4&&fc8sz9-jz8^aqsnx&xbno'

# SECURITY WARNING: don't run with debug turned on in production!


SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django.forms',
    
    'robots',
    # древо категорий
    'sitetree',
    # сортировка приложений
    'admin_reorder',
    # редактор текста
    'ckeditor',
    'ckeditor_uploader',
    #приложения
    'stranica',
    'prostopages',
    # работа с кешем картинок
    'sorl.thumbnail',
    # главная страница
    'solo',
    #сортировка перетаскиванием
    'adminsortable2',
    #работа с постгрес
    'django.contrib.postgres',



]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',

    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',

    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    
]

HTML_MINIFY  =  True

EXCLUDE_FROM_MINIFYING = ('^svg_admin/',)
KEEP_COMMENTS_ON_MINIFYING  =  True


ROOT_URLCONF = 'wiki.urls'

WSGI_APPLICATION = 'wiki.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/



ADMIN_REORDER = (
    # Keep original label and models
    # Rename app
    #{'app': 'auth', 'label': 'Authorisation'},
    # Reorder app models
    #{'app': 'auth', 'models': ('auth.User', 'auth.Group')},
    # Exclude models
    #{'app': 'auth', 'models': ('auth.User', )},
    # Cross-linked models
    #{'app': 'auth', 'models': ('auth.User', 'sites.Site')},
    # models with custom name
    # {'app': 'auth', 'models': (
    #     'auth.Group',
    #    {'model': 'auth.User', 'label': 'Staff'},
    # )},
    'stranica',
    'prostopages',
    'sitetree',
    'robots',
    {'app': 'auth', 'models': ('auth.User', 'auth.Group', 'sites.Site')},
)




CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
CKEDITOR_UPLOAD_PATH = 'upload/'

CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {

   'default': {
       'skin': 'moono-lisa',
       'width': "1000px",
       'height':'250px',
       # 'skin': 'office2013',
       'allowedContent': True,
       'config.allowedContent': True,




       'toolbar_Basic': [
           ['Source', '-', 'Bold', 'Italic', ]
       ],
       'toolbar_YourCustomToolbarConfig': [
        {'name': 'styles', 'items': ['Styles',  'Format', 'Font', 'FontSize', 'CodeSnippet']},
        {'name': 'colors', 'items': ['TextColor', 'BGColor']},
        {'name': 'tools', 'items': ['Maximize', 'ShowBlocks','Preview',]},

           {'name': 'document', 'items': ['Source', '-', 'Save', 'Print', '-',]},
           {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},


           '/',
           {'name': 'basicstyles',
            'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
           {'name': 'paragraph',
            'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                      'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                     ]},
           {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
           {'name': 'insert',
            'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe','Replace', 'SelectAll']},

       ],
       'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here

        #'height': 291,
        #'width': '100%',
        #'filebrowserWindowHeight': 725,
        #'filebrowserWindowWidth': 940,
        #'toolbarCanCollapse': True,
        #'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
       'tabSpaces': 4,

       'removePlugins': 'stylesheetparser',
       'extraPlugins': ','.join(
           [
               # your extra plugins here
               'div',
               'autolink',
               'autoembed',
               'embedsemantic',
               'autogrow',
               # 'devtools',
               'widget',
               'lineutils',
               'clipboard',
               'dialog',
               'dialogui',
               'elementspath',
               'codesnippet',
               'simage',
           ]),
   }
}
