# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 11:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prostopage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('text_block', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e')),
                ('active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c')),
                ('nomer_id', models.IntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0438')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('template_name', models.CharField(blank=True, help_text="\u041f\u0440\u0438\u043c\u0435\u0440: 'flatpages/contact_page.html'. \u0415\u0441\u043b\u0438 \u043d\u0435 \u0443\u043a\u0430\u0437\u0430\u043d\u043e,  \u0441\u0438\u0441\u0442\u0435\u043c\u0430 \u0431\u0443\u0434\u0435\u0442 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c 'flatpages/default.html'.", max_length=70, verbose_name='\u0412\u044b\u0431\u043e\u0440 \u0448\u0430\u0431\u043b\u043e\u043d\u0430')),
                ('title_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u0430\u0439\u0442\u043b')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u0414\u0435\u0441\u043a\u0440\u0438\u043f\u0448\u043e\u043d')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u0435\u0439\u0432\u043e\u0440\u0434\u0441')),
            ],
            options={
                'ordering': ['nomer_id'],
                'verbose_name': '\u041f\u0440\u043e\u0441\u0442\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b2',
                'verbose_name_plural': '\u041f\u0440\u043e\u0441\u0442\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b2',
            },
        ),
    ]
