# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostopages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prostopage',
            options={'ordering': ['nomer_id'], 'verbose_name': '\u041f\u0440\u043e\u0441\u0442\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b', 'verbose_name_plural': '\u041f\u0440\u043e\u0441\u0442\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'},
        ),
        migrations.AlterField(
            model_name='prostopage',
            name='template_name',
            field=models.CharField(blank=True, help_text="\u041f\u0440\u0438\u043c\u0435\u0440: 'prostopages/prostopages2.html'. \u0415\u0441\u043b\u0438 \u043d\u0435 \u0443\u043a\u0430\u0437\u0430\u043d\u043e,  \u0441\u0438\u0441\u0442\u0435\u043c\u0430 \u0431\u0443\u0434\u0435\u0442 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c 'prostopages/prostopages.html'.", max_length=70, verbose_name='\u0412\u044b\u0431\u043e\u0440 \u0448\u0430\u0431\u043b\u043e\u043d\u0430'),
        ),
    ]
