# Generated by Django 2.1 on 2018-09-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prostopages', '0002_auto_20171221_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prostopage',
            name='url',
        ),
        migrations.AddField(
            model_name='prostopage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='prostopage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
